### ISSUE TITLE
issue when importing

### ISSUE THREAD

**Issue by PwccaCode** [shrddr/shrddr.github.io#4]
Hello there, im been facing a problem when trying to import my worker settings,

When i import the screen goes black, there is no map anymore and i get a few erros on console

```
TypeError: Cannot read properties of undefined (reading 'CP')
    at Proxy.dijkstraPath (index.99f286e8.js:17:19971)
    at Proxy.<anonymous> (index.99f286e8.js:7:5509)
    at e.<computed> (index.99f286e8.js:7:2617)
    at index.99f286e8.js:17:537
    at Array.forEach (<anonymous>)
    at Proxy.pzJobs (index.99f286e8.js:17:349)
    at QT.fn (index.99f286e8.js:7:4340)
    at QT.run (index.99f286e8.js:1:5534)
    at get value [as value] (index.99f286e8.js:1:13599)
    at Object.get (index.99f286e8.js:1:7798)

index.99f286e8.js:1 TypeError: Cannot read properties of undefined (reading 'itemkeys')
    at Proxy.townsStoreItemkeys (index.99f286e8.js:17:2358)
    at QT.fn (index.99f286e8.js:7:4340)
    at QT.run (index.99f286e8.js:1:5534)
    at get value [as value] (index.99f286e8.js:1:13599)
    at Object.get (index.99f286e8.js:1:7798)
    at index.99f286e8.js:17:2855
    at Proxy.forEach (<anonymous>)
    at Proxy.townsInfra (index.99f286e8.js:17:2768)
    at QT.fn (index.99f286e8.js:7:4340)
    at QT.run (index.99f286e8.js:1:5534)
```

This is my worker profile 

https://pastebin.com/bYkJQbC3

i got by running the script listed on the website

**Comment by shrddr** [comment]
Thanks for reporting, unfortunately away from home now, only coming back in 2 weeks

**Comment by shrddr** [comment]
caused by unknown plantzone 1831, probably a temporary event node, will now remove jobs like these when importing
